allowBuilds:
  "@prisma/client": true
  '@prisma/engines': set this to true or false
  "@tailwindcss/oxide": true
  bcryptjs: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true
